apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mongo
        name: db
        volumeMounts:
        - mountPath: /data/db
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}
