apiVersion: v1
kind: Service
metadata:
  name: node-micro
spec:
  type: NodePort
  ports:
  - name: "node-micro-service"
    port: 5005
    targetPort: 3000
    nodePort: 31005
  selector:
    app: node-micro
---
apiVersion: v1
kind: Service
metadata:
  name: node-micro-external
spec:
  type: LoadBalancer
  ports:
  - name: "node-micro-service"
    port: 8005
    targetPort: 3000
  selector:
    app: node-micro
